"""Initial

Revision ID: 9dc309814638
Revises:
Create Date: 2026-04-10 20:29:02.579065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9dc309814638"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=15, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="paymentstatusenum"
            ),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(
        "ix_transactions_currency_status",
        "transactions",
        ["currency", "status"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_processed_at", "transactions", ["processed_at"], unique=False
    )
    op.create_index(
        "ix_transactions_status_processed_at",
        "transactions",
        ["status", "processed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_status_processed_at", table_name="transactions")
    op.drop_index("ix_transactions_processed_at", table_name="transactions")
    op.drop_index("ix_transactions_currency_status", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
